/* This file is part of Libsvgtiny
 * Licensed under the MIT License,
 *                http://opensource.org/licenses/mit-license.php
 * Copyright 2012 Daniel Silverstone <dsilvers@netsurf-browser.org>
 */

#ifndef SVGTINY_STRING_ACTION
#error No action defined
#endif

SVGTINY_STRING_ACTION(svg)
SVGTINY_STRING_ACTION(viewBox)
SVGTINY_STRING_ACTION(a)
SVGTINY_STRING_ACTION(d)
SVGTINY_STRING_ACTION(g)
SVGTINY_STRING_ACTION(r)
SVGTINY_STRING_ACTION(cx)
SVGTINY_STRING_ACTION(cy)
SVGTINY_STRING_ACTION(rx)
SVGTINY_STRING_ACTION(ry)
SVGTINY_STRING_ACTION(x1)
SVGTINY_STRING_ACTION(y1)
SVGTINY_STRING_ACTION(x2)
SVGTINY_STRING_ACTION(y2)
SVGTINY_STRING_ACTION(path)
SVGTINY_STRING_ACTION(points)
SVGTINY_STRING_ACTION(rect)
SVGTINY_STRING_ACTION(circle)
SVGTINY_STRING_ACTION(ellipse)
SVGTINY_STRING_ACTION(line)
SVGTINY_STRING_ACTION(polyline)
SVGTINY_STRING_ACTION(polygon)
SVGTINY_STRING_ACTION(text)
SVGTINY_STRING_ACTION(tspan)
